version: '3.8'

services:
  frontend:
    image: web-app:latest
    build:
      context: .
      # args:
      #   VITE_API_URL: ${VITE_API_URL}
      #   VITE_SOCKET_URL: ${VITE_SOCKET_URL}
      dockerfile: Dockerfile.vercel
    ports:
      - "5001:80"
    restart: unless-stopped