version: '3.8'

services:
  frontend:
    image: yolo-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - "5001:80"
    restart: unless-stopped